import {
  MarineCompany,
  Equipment,
  Order,
  AdminUser,
  Message,
  Dashboard,
} from './types'

export const mockCompanies: MarineCompany[] = [
  {
    id: 'comp-001',
    name: 'Atlantic Marine Solutions',
    location: 'Lagos',
    country: 'Nigeria',
    contactEmail: 'info@atlanticmarine.ng',
    phone: '+234 701 234 5678',
    logo: '/companies/atlantic.png',
    banner: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    rating: 4.8,
    totalEquipment: 24,
    totalOrders: 142,
    totalRevenue: 2450000,
    joinedDate: new Date('2022-03-15'),
    description: 'Leading provider of offshore drilling equipment and vessel leasing services.',
  },
  {
    id: 'comp-002',
    name: 'Gulf Cargo Transport',
    location: 'Port Harcourt',
    country: 'Nigeria',
    contactEmail: 'contact@gulfcargo.ng',
    phone: '+234 802 567 8901',
    logo: '/companies/gulf.png',
    verificationStatus: 'verified',
    rating: 4.6,
    totalEquipment: 18,
    totalOrders: 98,
    totalRevenue: 1890000,
    joinedDate: new Date('2022-07-20'),
    description: 'Specialized in container handling equipment and cargo logistics.',
  },
  {
    id: 'comp-003',
    name: 'Deep Sea Exploration',
    location: 'Calabar',
    country: 'Nigeria',
    contactEmail: 'sales@deepseaexp.ng',
    phone: '+234 706 345 6789',
    logo: '/companies/deepsea.png',
    verificationStatus: 'verified',
    rating: 4.9,
    totalEquipment: 31,
    totalOrders: 156,
    totalRevenue: 3120000,
    joinedDate: new Date('2021-11-10'),
    description: 'Premium diving gear, submersible equipment, and oceanographic tools.',
  },
  {
    id: 'comp-004',
    name: 'Coastal Navigation Ltd',
    location: 'Lagos',
    country: 'Nigeria',
    contactEmail: 'ops@coastalnav.ng',
    phone: '+234 703 789 0123',
    logo: '/companies/coastal.png',
    verificationStatus: 'pending',
    rating: 0,
    totalEquipment: 12,
    totalOrders: 0,
    totalRevenue: 0,
    joinedDate: new Date('2024-01-05'),
    description: 'Navigation systems and maritime communication equipment provider.',
  },
  {
    id: 'comp-005',
    name: 'Maritime Safety Systems',
    location: 'Lagos',
    country: 'Nigeria',
    contactEmail: 'support@marinesafety.ng',
    phone: '+234 708 123 4567',
    logo: '/companies/safety.png',
    verificationStatus: 'verified',
    rating: 4.7,
    totalEquipment: 22,
    totalOrders: 118,
    totalRevenue: 2180000,
    joinedDate: new Date('2022-05-22'),
    description: 'Safety equipment, life jackets, and emergency response systems.',
  },
]

export const mockEquipment: Equipment[] = [
  {
    id: 'eq-001',
    companyId: 'comp-001',
    name: 'Offshore Drilling Platform',
    category: 'vessels',
    description: 'Semi-submersible drilling platform with advanced positioning system',
    condition: 'excellent',
    availability: 'available',
    hourlyRate: 15000,
    dailyRate: 280000,
    monthlyRate: 7500000,
    images: ['/equipment/drilling-platform.jpg'],
    specifications: {
      displacement: '14,100 tons',
      water_depth_capability: '3,000m',
      crew_capacity: '200',
      deck_area: '7,000 sqm',
    },
    weight: 14100,
    yearManufactured: 2018,
    maintenanceDate: new Date('2024-01-15'),
    createdAt: new Date('2023-06-10'),
  },
  {
    id: 'eq-002',
    companyId: 'comp-001',
    name: 'Deck Crane 500T',
    category: 'cargo-equipment',
    description: 'Heavy-duty deck crane for offshore operations',
    condition: 'excellent',
    availability: 'rented',
    hourlyRate: 2500,
    dailyRate: 45000,
    monthlyRate: 1200000,
    images: ['/equipment/crane-500.jpg'],
    specifications: {
      capacity: '500 tons',
      outreach: '60m',
      height: '80m',
      duty_cycle: '120 cycles/hour',
    },
    weight: 850,
    yearManufactured: 2020,
    createdAt: new Date('2023-08-15'),
  },
  {
    id: 'eq-003',
    companyId: 'comp-002',
    name: 'Container Spreader Bar',
    category: 'cargo-equipment',
    description: 'Automated container spreader bar for efficient loading/unloading',
    condition: 'good',
    availability: 'available',
    hourlyRate: 500,
    dailyRate: 8000,
    monthlyRate: 200000,
    images: ['/equipment/spreader-bar.jpg'],
    specifications: {
      max_container_size: '40ft',
      auto_lock_system: 'Yes',
      weight: '12 tons',
    },
    createdAt: new Date('2023-09-20'),
  },
  {
    id: 'eq-004',
    companyId: 'comp-003',
    name: 'Technical Diving Suit',
    category: 'diving-gear',
    description: 'Professional dry suit for technical deep sea diving',
    condition: 'excellent',
    availability: 'available',
    hourlyRate: 50,
    dailyRate: 300,
    monthlyRate: 5000,
    images: ['/equipment/dive-suit.jpg'],
    specifications: {
      material: 'Laminated neoprene',
      thickness: '7mm',
      max_depth: '300m',
      sizes_available: 'XS to 3XL',
    },
    createdAt: new Date('2023-10-05'),
  },
  {
    id: 'eq-005',
    companyId: 'comp-003',
    name: 'Submersible ROV 6000',
    category: 'diving-gear',
    description: 'Remotely operated vehicle for deep ocean exploration',
    condition: 'excellent',
    availability: 'available',
    hourlyRate: 8000,
    dailyRate: 150000,
    monthlyRate: 4000000,
    images: ['/equipment/rov-6000.jpg'],
    specifications: {
      max_depth: '6000m',
      dimensions: '3.5m x 2.8m x 2.1m',
      camera_resolution: '8K',
      manipulator_arms: '2',
    },
    weight: 3200,
    yearManufactured: 2021,
    createdAt: new Date('2023-11-10'),
  },
  {
    id: 'eq-006',
    companyId: 'comp-005',
    name: 'Life Raft 50 Person',
    category: 'safety',
    description: 'SOLAS compliant life raft for emergency evacuation',
    condition: 'excellent',
    availability: 'available',
    hourlyRate: 100,
    dailyRate: 600,
    monthlyRate: 12000,
    images: ['/equipment/life-raft.jpg'],
    specifications: {
      capacity: '50 persons',
      certification: 'SOLAS A',
      weight: '850 kg',
      pack_dimensions: '2.5m x 2.5m x 2.8m',
    },
    createdAt: new Date('2023-12-01'),
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-001',
    equipmentId: 'eq-001',
    companyId: 'comp-001',
    rentedBy: 'Shell Nigeria',
    renterEmail: 'rental@shell.com',
    renterPhone: '+234 701 234 5678',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-03-15'),
    status: 'active',
    totalPrice: 4200000,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    notes: 'Offshore drilling project in Bonga field',
    createdAt: new Date('2024-01-28'),
  },
  {
    id: 'order-002',
    equipmentId: 'eq-002',
    companyId: 'comp-001',
    rentedBy: 'Chevron Nigeria',
    renterEmail: 'ops@chevron.ng',
    startDate: new Date('2024-02-10'),
    endDate: new Date('2024-02-20'),
    status: 'active',
    totalPrice: 450000,
    paymentMethod: 'credit_card',
    paymentStatus: 'paid',
    createdAt: new Date('2024-02-08'),
  },
  {
    id: 'order-003',
    equipmentId: 'eq-003',
    companyId: 'comp-002',
    rentedBy: 'Lagos Port Authority',
    renterEmail: 'logistics@lpa.gov.ng',
    startDate: new Date('2024-02-05'),
    endDate: new Date('2024-02-19'),
    status: 'active',
    totalPrice: 64000,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'order-004',
    equipmentId: 'eq-005',
    companyId: 'comp-003',
    rentedBy: 'Ocean Research Institute',
    renterEmail: 'research@oceaninst.org',
    startDate: new Date('2024-02-15'),
    endDate: new Date('2024-03-20'),
    status: 'confirmed',
    totalPrice: 3000000,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'pending',
    notes: 'Mariana Trench exploration expedition',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'order-005',
    equipmentId: 'eq-004',
    companyId: 'comp-003',
    rentedBy: 'John Smith',
    renterEmail: 'john.smith@email.com',
    renterPhone: '+234 705 111 2222',
    startDate: new Date('2024-01-20'),
    endDate: new Date('2024-01-25'),
    status: 'completed',
    totalPrice: 1500,
    paymentMethod: 'credit_card',
    paymentStatus: 'paid',
    createdAt: new Date('2024-01-18'),
  },
]

export const mockAdminUsers: AdminUser[] = [
  {
    id: 'admin-001',
    email: 'admin@muskmover.ng',
    name: 'Chioma Okoro',
    role: 'admin',
    status: 'active',
    lastLogin: new Date('2024-02-16'),
    createdAt: new Date('2023-01-15'),
    avatar: '/avatars/chioma.png',
  },
  {
    id: 'admin-002',
    email: 'manager@muskmover.ng',
    name: 'David Okonkwo',
    role: 'manager',
    status: 'active',
    lastLogin: new Date('2024-02-16'),
    createdAt: new Date('2023-06-20'),
    avatar: '/avatars/david.png',
  },
  {
    id: 'admin-003',
    email: 'support@muskmover.ng',
    name: 'Grace Adeyemi',
    role: 'viewer',
    status: 'active',
    lastLogin: new Date('2024-02-15'),
    createdAt: new Date('2023-09-10'),
    avatar: '/avatars/grace.png',
  },
]

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    senderId: 'comp-001',
    senderName: 'Atlantic Marine Solutions',
    recipientId: 'admin-001',
    companyId: 'comp-001',
    subject: 'Equipment Maintenance Schedule',
    body: 'We need to schedule maintenance for our drilling platform. Can we arrange this for next week?',
    isRead: false,
    createdAt: new Date('2024-02-16 10:30'),
  },
  {
    id: 'msg-002',
    senderId: 'admin-001',
    senderName: 'Chioma Okoro',
    recipientId: 'comp-002',
    companyId: 'comp-002',
    subject: 'RE: New Equipment Listing',
    body: 'Your new container spreader bars have been approved and are now live on the marketplace.',
    isRead: true,
    createdAt: new Date('2024-02-15 14:45'),
  },
  {
    id: 'msg-003',
    senderId: 'comp-003',
    senderName: 'Deep Sea Exploration',
    recipientId: 'admin-002',
    companyId: 'comp-003',
    subject: 'Payment Discrepancy',
    body: 'We noticed a discrepancy in our February payment. Can you help us investigate?',
    isRead: false,
    createdAt: new Date('2024-02-16 08:15'),
  },
]

export const mockDashboardStats: Dashboard = {
  totalCompanies: mockCompanies.length,
  totalEquipment: mockEquipment.length,
  activeOrders: mockOrders.filter((o) => o.status === 'active').length,
  monthlyRevenue: 8604000,
  pendingVerifications: mockCompanies.filter((c) => c.verificationStatus === 'pending')
    .length,
  averageRating: 4.74,
}

/* Helper functions */
export const getCompanyById = (id: string): MarineCompany | undefined => {
  return mockCompanies.find((c) => c.id === id)
}

export const getEquipmentByCompanyId = (companyId: string): Equipment[] => {
  return mockEquipment.filter((e) => e.companyId === companyId)
}

export const getOrdersByCompanyId = (companyId: string): Order[] => {
  return mockOrders.filter((o) => o.companyId === companyId)
}

export const getOrdersByEquipmentId = (equipmentId: string): Order[] => {
  return mockOrders.filter((o) => o.equipmentId === equipmentId)
}

export const getRecentMessages = (limit: number = 5): Message[] => {
  return mockMessages.slice(0, limit)
}
