import {
  MarineCompany,
  Equipment,
  Order,
  AdminUser,
  Message,
  Dashboard,
} from './types'

export const mockCompanies: MarineCompany[] = [
  {
    id: '1',
    name: 'Atlantic Marine Solutions',
    location: 'Lagos',
    country: 'Nigeria',
    contactEmail: 'info@atlanticmarine.ng',
    phone: '+234 701 234 5678',
    logo: '/companies/atlantic.png',
    banner: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80',
    status: 'Approved',
    rating: 4.8,
    totalOrders: 142,
    totalRevenue: 2450000,
    description: 'Leading provider of offshore drilling equipment and vessel leasing services.',
    createdAt: '2022-03-15T00:00:00Z',
    updatedAt: '2022-03-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Gulf Cargo Transport',
    location: 'Port Harcourt',
    country: 'Nigeria',
    contactEmail: 'contact@gulfcargo.ng',
    phone: '+234 802 567 8901',
    logo: '/companies/gulf.png',
    status: 'Approved',
    rating: 4.6,
    totalEquipment: 18,
    totalOrders: 98,
    totalRevenue: 1890000,
    description: 'Specialized in container handling equipment and cargo logistics.',
    createdAt: '2022-07-20T00:00:00Z',
    updatedAt: '2022-07-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'Deep Sea Exploration',
    location: 'Calabar',
    country: 'Nigeria',
    contactEmail: 'sales@deepseaexp.ng',
    phone: '+234 706 345 6789',
    logo: '/companies/deepsea.png',
    status: 'Approved',
    rating: 4.9,
    totalEquipment: 31,
    totalOrders: 156,
    totalRevenue: 3120000,
    description: 'Premium diving gear, submersible equipment, and oceanographic tools.',
    createdAt: '2021-11-10T00:00:00Z',
    updatedAt: '2021-11-10T00:00:00Z',
  },
  {
    id: '4',
    name: 'Coastal Navigation Ltd',
    location: 'Lagos',
    country: 'Nigeria',
    contactEmail: 'ops@coastalnav.ng',
    phone: '+234 703 789 0123',
    logo: '/companies/coastal.png',
    status: 'Pending',
    rating: 0,
    totalEquipment: 12,
    totalOrders: 0,
    totalRevenue: 0,
    description: 'Navigation systems and maritime communication equipment provider.',
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: '5',
    name: 'Maritime Safety Systems',
    location: 'Lagos',
    country: 'Nigeria',
    contactEmail: 'support@marinesafety.ng',
    phone: '+234 708 123 4567',
    logo: '/companies/safety.png',
    status: 'Approved',
    rating: 4.7,
    totalEquipment: 22,
    totalOrders: 118,
    totalRevenue: 2180000,
    description: 'Safety equipment, life jackets, and emergency response systems.',
    createdAt: '2022-05-22T00:00:00Z',
    updatedAt: '2022-05-22T00:00:00Z',
  },
]

export const mockEquipment: Equipment[] = [
  {
    id: 1,
    companyId: 1,
    name: 'Offshore Drilling Platform',
    category: 'vessels',
    details: 'Semi-submersible drilling platform with advanced positioning system',
    condition: 'excellent',
    status: 'available',
    hourlyRate: 15000,
    dailyRate: 280000,
    monthlyRate: 7500000,
    images: ['/equipment/drilling-platform.jpg'],
    weight: 14100,
    yearManufactured: 2018,
    createdAt: '2023-06-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 2,
    companyId: 1,
    name: 'Deck Crane 500T',
    category: 'cargo-equipment',
    details: 'Heavy-duty deck crane for offshore operations',
    condition: 'excellent',
    status: 'rented',
    hourlyRate: 2500,
    dailyRate: 45000,
    monthlyRate: 1200000,
    images: ['/equipment/crane-500.jpg'],
    weight: 850,
    yearManufactured: 2020,
    createdAt: '2023-08-15T00:00:00Z',
  },
  {
    id: 3,
    companyId: 2,
    name: 'Container Spreader Bar',
    category: 'cargo-equipment',
    details: 'Automated container spreader bar for efficient loading/unloading',
    condition: 'good',
    status: 'available',
    hourlyRate: 500,
    dailyRate: 8000,
    monthlyRate: 200000,
    images: ['/equipment/spreader-bar.jpg'],
    weight: 12,
    yearManufactured: 2021,
    createdAt: '2023-09-20T00:00:00Z',
  },
  {
    id: 4,
    companyId: 3,
    name: 'Technical Diving Suit',
    category: 'diving-gear',
    details: 'Professional dry suit for technical deep sea diving',
    condition: 'excellent',
    status: 'available',
    hourlyRate: 50,
    dailyRate: 300,
    monthlyRate: 5000,
    images: ['/equipment/dive-suit.jpg'],
    weight: 5,
    yearManufactured: 2022,
    createdAt: '2023-10-05T00:00:00Z',
  },
  {
    id: 5,
    companyId: 3,
    name: 'Submersible ROV 6000',
    category: 'diving-gear',
    details: 'Remotely operated vehicle for deep ocean exploration',
    condition: 'excellent',
    status: 'available',
    hourlyRate: 8000,
    dailyRate: 150000,
    monthlyRate: 4000000,
    images: ['/equipment/rov-6000.jpg'],
    weight: 3200,
    yearManufactured: 2021,
    createdAt: '2023-11-10T00:00:00Z',
  },
  {
    id: 6,
    companyId: 5,
    name: 'Life Raft 50 Person',
    category: 'safety',
    details: 'SOLAS compliant life raft for emergency evacuation',
    condition: 'excellent',
    status: 'available',
    hourlyRate: 100,
    dailyRate: 600,
    monthlyRate: 12000,
    images: ['/equipment/life-raft.jpg'],
    weight: 850,
    yearManufactured: 2022,
    createdAt: '2023-12-01T00:00:00Z',
  },
]

export const mockOrders: Order[] = [
  {
    id: 1,
    orderNumber: 'ORD-001',
    renterName: 'Shell Nigeria',
    renterEmail: 'rental@shell.com',
    equipmentId: 1,
    vesselId: 0,
    startDate: '2024-02-01T00:00:00Z',
    endDate: '2024-03-15T00:00:00Z',
    status: 'active',
    totalPrice: 4200000,
    paymentStatus: 'paid',
    createdAt: '2024-01-28T00:00:00Z',
  },
  {
    id: 2,
    orderNumber: 'ORD-002',
    renterName: 'Chevron Nigeria',
    renterEmail: 'ops@chevron.ng',
    equipmentId: 2,
    vesselId: 0,
    startDate: '2024-02-10T00:00:00Z',
    endDate: '2024-02-20T00:00:00Z',
    status: 'active',
    totalPrice: 450000,
    paymentStatus: 'paid',
    createdAt: '2024-02-08T00:00:00Z',
  },
  {
    id: 3,
    orderNumber: 'ORD-003',
    renterName: 'Lagos Port Authority',
    renterEmail: 'logistics@lpa.gov.ng',
    equipmentId: 3,
    vesselId: 0,
    startDate: '2024-02-05T00:00:00Z',
    endDate: '2024-02-19T00:00:00Z',
    status: 'active',
    totalPrice: 64000,
    paymentStatus: 'paid',
    createdAt: '2024-02-03T00:00:00Z',
  },
  {
    id: 4,
    orderNumber: 'ORD-004',
    renterName: 'Ocean Research Institute',
    renterEmail: 'research@oceaninst.org',
    equipmentId: 5,
    vesselId: 0,
    startDate: '2024-02-15T00:00:00Z',
    endDate: '2024-03-20T00:00:00Z',
    status: 'confirmed',
    totalPrice: 3000000,
    paymentStatus: 'pending',
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 5,
    orderNumber: 'ORD-005',
    renterName: 'John Smith',
    renterEmail: 'john.smith@email.com',
    equipmentId: 4,
    vesselId: 0,
    startDate: '2024-01-20T00:00:00Z',
    endDate: '2024-01-25T00:00:00Z',
    status: 'completed',
    totalPrice: 1500,
    paymentStatus: 'paid',
    createdAt: '2024-01-18T00:00:00Z',
  },
]

export const mockAdminUsers: AdminUser[] = [
  {
    id: 'admin-001',
    email: 'admin@muskmover.ng',
    name: 'Chioma Okoro',
    role: 'admin',
    status: 'active',
    lastLogin: new Date('2024-02-16'),
    createdAt: new Date('2023-01-15'),
    avatar: '/avatars/chioma.png',
  },
  {
    id: 'admin-002',
    email: 'manager@muskmover.ng',
    name: 'David Okonkwo',
    role: 'manager',
    status: 'active',
    lastLogin: new Date('2024-02-16'),
    createdAt: new Date('2023-06-20'),
    avatar: '/avatars/david.png',
  },
  {
    id: 'admin-003',
    email: 'support@muskmover.ng',
    name: 'Grace Adeyemi',
    role: 'viewer',
    status: 'active',
    lastLogin: new Date('2024-02-15'),
    createdAt: new Date('2023-09-10'),
    avatar: '/avatars/grace.png',
  },
]

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    senderId: '1',
    senderName: 'Atlantic Marine Solutions',
    recipientId: 'admin-001',
    companyId: '1',
    subject: 'Equipment Maintenance Schedule',
    body: 'We need to schedule maintenance for our drilling platform. Can we arrange this for next week?',
    isRead: false,
    createdAt: new Date('2024-02-16T10:30:00Z'),
  },
  {
    id: 'msg-002',
    senderId: 'admin-001',
    senderName: 'Chioma Okoro',
    recipientId: '2',
    companyId: '2',
    subject: 'RE: New Equipment Listing',
    body: 'Your new container spreader bars have been approved and are now live on the marketplace.',
    isRead: true,
    createdAt: new Date('2024-02-15T14:45:00Z'),
  },
  {
    id: 'msg-003',
    senderId: '3',
    senderName: 'Deep Sea Exploration',
    recipientId: 'admin-002',
    companyId: '3',
    subject: 'Payment Discrepancy',
    body: 'We noticed a discrepancy in our February payment. Can you help us investigate?',
    isRead: false,
    createdAt: new Date('2024-02-16T08:15:00Z'),
  },
]

export const mockDashboardStats: Dashboard = {
  totalCompanies: mockCompanies.length,
  totalEquipment: mockEquipment.length,
  totalOrders: mockOrders.length,
  activeOrders: mockOrders.filter((o) => o.status === 'active').length,
  monthlyRevenue: 8604000,
  pendingVerifications: mockCompanies.filter((c) => c.status === 'Pending').length,
  averageRating: 4.74,
}

/* Helper functions */
export const getCompanyById = (id: string): MarineCompany | undefined => {
  return mockCompanies.find((c) => c.id === id)
}

export const getEquipmentByCompanyId = (companyId: number): Equipment[] => {
  return mockEquipment.filter((e) => e.companyId === companyId)
}

export const getOrdersByEquipmentId = (equipmentId: number): Order[] => {
  return mockOrders.filter((o) => o.equipmentId === equipmentId)
}

export const getRecentMessages = (limit: number = 5): Message[] => {
  return mockMessages.slice(0, limit)
}
